#!/bin/bash

input=$(echo "$1" | sed 's|www.||')

# Checks to see if enter ip falls between 0-9 for 1 to 3 places.

# Check to see if IP entered is valid.
function valid_ip {  
	
    local  input=$1
    local  status=1

    if [[ $input =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        # Break the IP into an array
        IFS='.' read -r -a ip <<< "$input"
    
        # Check to see if ip is equal to or lower than 255.
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        status="$?"
    fi
    
        return $status
}

# Checks to see if domain entered is valid.
function valid_domain {

    host "$input" 2>&1 > /dev/null 
    return $?
}
    
# Runs several dig queries and assigns the results to variables.

function digParser {
    dig_a=$(dig +noall +answer "$domain" a | grep "A" | awk '{$1=$2=$3=""; print $0}')
    dig_mx=$(dig +noall +answer "$domain" mx | grep "MX" | awk '{$1=$2=$3=""; print $0}')
}	

# Runs several whois queries and assigns the results to variables.
function whoisParser {
    whoisNS=$(echo "$rawWhois" | grep -m 2 "Name Server")
    whoisRegistrar=$(echo "$rawWhois" | grep -m 1 "Registrar:")
    whoisRegistrant=$(echo "$rawWhois" | grep -m 1 "Registrant")
    whoisReseller=$(echo "$rawWhois" | grep -m 1 "Reseller:")
    whoisExpDate=$(echo "$rawWhois" | grep -m 1 "Expiration")
}

if valid_ip "$input"; then
    # Assign the passed variable to ip.
    echo "==> Valid IP Address found!"
    echo "==> Running reverse dig on IP Address ..."
    
    dig -x "$input" | grep -m 2 "PTR" | tail -n +2

    elif valid_domain "$input"; then

    # Assign the passed variable to domain.
    domain="$input"

    rawWhois="$(whois "$domain")"

    echo ""
    echo "==> Valid Domain name found."
    echo "==> Running dig on domain "$domain" ..."

    # Prints dig variables.
    digParser
    echo "$dig_a" | awk '{$1=$1};1' 
    echo "$dig_mx" | awk '{$1=$1};1' | sed 's|\(.*\).|\1 |'

    echo ""

    echo "==> Running whois on domain "$domain" ..."

    # Prints whois variables.
    whoisParser

    echo "$whoisNS" | awk '{$1=$1};1'
    echo "$whoisRegistrar" | awk '{$1=$1};1' | tr -d '\.'
    echo "$whoisRegistrant" | awk '{$1=$1};1' | sed 's|Registry Registrant ID|Registrant|'
    echo "$whoisReseller" | awk '{$1=$1};1' | sed 's| http.*||'
    echo "$whoisExpDate" | awk '{$1=$1};1' | sed -e 's|Registrar Registration ||' | cut -b 1-27

    echo ""
else
    echo "Please enter a valid domain name or ip address."
fi
